import { readdir, readFile, writeFile, mkdir, stat } from "node:fs/promises";
import { join, resolve, dirname } from "node:path";

const root = resolve(import.meta.dir, "..", "..");
const dataDir = process.env.DATA_DIR
  ? resolve(process.env.DATA_DIR)
  : join(root, "output");
const targetFile = resolve(import.meta.dir, "..", "data-bundle.ts");

const baseTsvPath = join(root, "agent-inputs", "r4-base-resources-and-datatypes.tsv");
let baseArtifacts: { name: string; kind: string; abstract: boolean }[] = [];
try {
  const txt = await readFile(baseTsvPath, "utf8");
  baseArtifacts = txt.split(/\r?\n/).filter(Boolean).map((line) => {
    const [name, kind, _id, abs] = line.split("\t");
    return { name, kind, abstract: abs === "true" };
  });
} catch {
  console.warn(`No base artifact TSV at ${baseTsvPath}; coverage will be unknown.`);
}

// R4 maturity / normative status — read from a checked-in JSON map produced
// by `scripts/extract-r4-maturity.ts`. The R4 package itself is .gitignored,
// so committing the extracted JSON makes the data available in CI builds.
const maturityPath = resolve(import.meta.dir, "..", "r4-maturity.json");
type R4Maturity = { standardsStatus?: string; fmm?: number; wg?: string; normativeVersion?: string };
let r4Maturity: Record<string, R4Maturity> = {};
try {
  r4Maturity = JSON.parse(await readFile(maturityPath, "utf8"));
  console.log(`loaded maturity for ${Object.keys(r4Maturity).length} R4 artifacts from ${maturityPath}`);
} catch {
  console.warn(`No r4-maturity.json at ${maturityPath}; maturity facet will be unknown. Run scripts/extract-r4-maturity.ts to regenerate.`);
}

const files = (await readdir(dataDir)).filter((f) => f.endsWith(".report.json"));
const reports: any[] = [];
const parseFailures: { file: string; error: string }[] = [];
for (const f of files) {
  try {
    const p = join(dataDir, f);
    const [txt, st] = await Promise.all([readFile(p, "utf8"), stat(p)]);
    const parsed = JSON.parse(txt);
    parsed._mtimeMs = st.mtimeMs;
    reports.push(parsed);
  } catch (e) {
    parseFailures.push({ file: f, error: (e as Error).message });
    console.error(`failed to parse ${f}:`, (e as Error).message);
  }
}
reports.sort((a, b) => (a.artifactName ?? "").localeCompare(b.artifactName ?? ""));

const payload = {
  generatedAt: new Date().toISOString(),
  sourceDir: dataDir,
  baseArtifacts,
  r4Maturity,
  parseFailures,
  reports,
};

await mkdir(dirname(targetFile), { recursive: true });
const ts = `// AUTO-GENERATED by scripts/build-data.ts — do not edit by hand
import type { BundleData } from "./types";
export const bundle: BundleData = ${JSON.stringify(payload, null, 2)} as unknown as BundleData;
`;
await writeFile(targetFile, ts);
console.log(`bundled ${reports.length} report(s) from ${dataDir} → ${targetFile}`);
