import { readdir, readFile, writeFile, mkdir, stat } from "node:fs/promises";
import { join, resolve, dirname } from "node:path";

const root = resolve(import.meta.dir, "..", "..");
const dataDir = process.env.DATA_DIR
  ? resolve(process.env.DATA_DIR)
  : join(root, "output");
const targetFile = resolve(import.meta.dir, "..", "data-bundle.ts");

const baseTsvPath = join(root, "agent-inputs", "r4-base-resources-and-datatypes.tsv");
let baseArtifacts: { name: string; kind: string; abstract: boolean }[] = [];
try {
  const txt = await readFile(baseTsvPath, "utf8");
  baseArtifacts = txt.split(/\r?\n/).filter(Boolean).map((line) => {
    const [name, kind, _id, abs] = line.split("\t");
    return { name, kind, abstract: abs === "true" };
  });
} catch {
  console.warn(`No base artifact TSV at ${baseTsvPath}; coverage will be unknown.`);
}

// R4 maturity / normative status — scraped from the R4 StructureDefinition
// package extensions. Keyed by artifactName.
const r4PkgDir = join(root, "fhir-definitions", "r4-4.0.1", "package");
const STATUS_EXT = "http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status";
const FMM_EXT    = "http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm";
const WG_EXT     = "http://hl7.org/fhir/StructureDefinition/structuredefinition-wg";
const NORM_VER   = "http://hl7.org/fhir/StructureDefinition/structuredefinition-normative-version";

type R4Maturity = { standardsStatus?: string; fmm?: number; wg?: string; normativeVersion?: string };
const r4Maturity: Record<string, R4Maturity> = {};
try {
  const sdFiles = (await readdir(r4PkgDir)).filter((f) => f.startsWith("StructureDefinition-") && f.endsWith(".json"));
  for (const f of sdFiles) {
    try {
      const sd = JSON.parse(await readFile(join(r4PkgDir, f), "utf8"));
      if (!sd?.name) continue;
      const exts: any[] = sd.extension ?? [];
      const out: R4Maturity = {};
      for (const e of exts) {
        if (e.url === STATUS_EXT && e.valueCode) out.standardsStatus = e.valueCode;
        else if (e.url === FMM_EXT && typeof e.valueInteger === "number") out.fmm = e.valueInteger;
        else if (e.url === WG_EXT && e.valueCode) out.wg = e.valueCode;
        else if (e.url === NORM_VER && e.valueCode) out.normativeVersion = e.valueCode;
      }
      if (Object.keys(out).length > 0) r4Maturity[sd.name] = out;
    } catch (e) {
      // skip malformed defs
    }
  }
  console.log(`scanned ${Object.keys(r4Maturity).length} R4 artifacts for maturity`);
} catch {
  console.warn(`No R4 package at ${r4PkgDir}; maturity facet will be unknown.`);
}

const files = (await readdir(dataDir)).filter((f) => f.endsWith(".report.json"));
const reports: any[] = [];
const parseFailures: { file: string; error: string }[] = [];
for (const f of files) {
  try {
    const p = join(dataDir, f);
    const [txt, st] = await Promise.all([readFile(p, "utf8"), stat(p)]);
    const parsed = JSON.parse(txt);
    parsed._mtimeMs = st.mtimeMs;
    reports.push(parsed);
  } catch (e) {
    parseFailures.push({ file: f, error: (e as Error).message });
    console.error(`failed to parse ${f}:`, (e as Error).message);
  }
}
reports.sort((a, b) => (a.artifactName ?? "").localeCompare(b.artifactName ?? ""));

const payload = {
  generatedAt: new Date().toISOString(),
  sourceDir: dataDir,
  baseArtifacts,
  r4Maturity,
  parseFailures,
  reports,
};

await mkdir(dirname(targetFile), { recursive: true });
const ts = `// AUTO-GENERATED by scripts/build-data.ts — do not edit by hand
import type { BundleData } from "./types";
export const bundle: BundleData = ${JSON.stringify(payload, null, 2)} as unknown as BundleData;
`;
await writeFile(targetFile, ts);
console.log(`bundled ${reports.length} report(s) from ${dataDir} → ${targetFile}`);
